version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
        - VITE_AUTH0_CUSTOM_DOMAIN=${VITE_AUTH0_CUSTOM_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_CLIENT_2_TOKEN=${VITE_CLIENT_2_TOKEN}
    ports:
      - 3000:3000
